services:
  backend:
    build: todos-backend-server
    environment:
      - TODOS_PORT=80
      - TODOS_DATA=/opt/todos/data/todos.json
    volumes:
      - todos-data:/opt/todos/data
  frontend:
    build: todos-frontend
  proxy:
    build: ./proxy
    ports:
      - 8080:80

volumes:
  todos-data:
